#!/usr/bin/env python3
"""
Build categorized .swibank files for reMID.lv2 direct SID-Wizard playback.

This repo no longer uses the reMID ".conf instrument language" at runtime.
Instead, the LV2 plugin loads a .swibank mapping file that selects which
SID-Wizard .swi instrument to run for each MIDI Program Change.

Outputs:
  instruments/banks/bank-<id>-<page>.swibank
  instruments/banks/banks_index.json
  instruments/banks/drumkit-gm.swibank (small GM-style example)
"""

from __future__ import annotations

from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path
from typing import Dict, List
import argparse
import json


@dataclass(frozen=True)
class BankDef:
    id: str
    label: str
    patterns: list[str]


def load_rules(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def classify(filename: str, rules: dict) -> str:
    fn = filename.lower()
    for bank in rules.get("banks", []):
        for pat in bank.get("patterns", []):
            if fnmatch(fn, pat.lower()):
                return bank["id"]
    return rules.get("fallback_bank", {}).get("id", "misc")


def write_swibank(path: Path, name: str, base_dir: str, program_to_file: Dict[int, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# generated by converter/build_banks.py")
    lines.append("")
    lines.append("[meta]")
    lines.append(f"name={name}")
    lines.append(f"base={base_dir}")
    lines.append("")
    lines.append("[programs]")
    for p in sorted(program_to_file.keys()):
        lines.append(f"{p}={program_to_file[p]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_gm_drumkit(path: Path, base_dir: str) -> None:
    """
    Minimal example drumkit mapping. Feel free to customize.
    """
    lines: list[str] = []
    lines.append("# generated by converter/build_banks.py")
    lines.append("# Program 0 selects DRUMKIT:gm and maps a few common GM notes.")
    lines.append("")
    lines.append("[meta]")
    lines.append("name=GM Drumkit (example)")
    lines.append(f"base={base_dir}")
    lines.append("")
    lines.append("[programs]")
    lines.append("0=DRUMKIT:gm")
    lines.append("")
    lines.append("[drumkit:gm]")
    lines.append("36=bass-drum.swi")      # Kick
    lines.append("38=snare-tight.swi")    # Snare
    lines.append("40=snare-deep.swi")     # Snare 2
    lines.append("42=hihat-short.swi")    # Closed HH
    lines.append("46=hihat-openli.swi")   # Open HH
    lines.append("49=crash-shortf.swi")   # Crash
    lines.append("51=cymbal-light.swi")   # Ride-ish
    lines.append("39=clap-snare.swi")     # Clap
    lines.append("45=tom-containr.swi")   # Tom
    lines.append("41=tom-filtkbtr.swi")   # Low tom
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")

def write_builtin_drumkit(path: Path, base_dir: str) -> None:
    """
    "Built-in" drumkit mapping shipped with the plugin bundle.
    This is just a curated mapping to the available SID-Wizard drum-ish instruments.
    """
    lines: list[str] = []
    lines.append("# generated by converter/build_banks.py")
    lines.append("# Program 0 selects DRUMKIT:remid (curated built-in style map).")
    lines.append("")
    lines.append("[meta]")
    lines.append("name=Drumkit: reMID (built-in)")
    lines.append(f"base={base_dir}")
    lines.append("")
    lines.append("[programs]")
    lines.append("0=DRUMKIT:remid")
    lines.append("")
    lines.append("[drumkit:remid]")
    # Kicks
    lines.append("35=bass-drum.swi")
    lines.append("36=bass-drum.swi")
    # Snares / claps
    lines.append("38=snare-tight.swi")
    lines.append("40=snare-deep.swi")
    lines.append("39=clap-snare.swi")
    # Hats
    lines.append("42=hihat-short.swi")
    lines.append("44=hihat-acoust.swi")
    lines.append("46=hihat-openli.swi")
    # Cymbals
    lines.append("49=crash-shortf.swi")
    lines.append("51=cymbal-light.swi")
    # Toms
    lines.append("41=tom-filtkbtr.swi")
    lines.append("43=tom-containr.swi")
    lines.append("45=tom-containr.swi")
    # Perc
    lines.append("54=tamburin.swi")
    lines.append("56=agogo.swi")
    lines.append("60=agogo.swi")
    lines.append("63=conga.swi")
    lines.append("64=conga.swi")
    lines.append("65=conga-clean.swi")
    lines.append("66=conga-wavy.swi")
    lines.append("67=agogo.swi")
    lines.append("70=shaker.swi")
    lines.append("76=woodblock.swi")
    lines.append("77=woodblock.swi")
    lines.append("78=agogo.swi")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent

    ap = argparse.ArgumentParser()
    ap.add_argument("--rules", default=str(repo_root / "converter" / "bank_rules.json"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    rules = load_rules(Path(args.rules))
    input_dir = (repo_root / rules.get("input_dir", "converter/sidwizard_instruments")).resolve()
    output_dir = (repo_root / rules.get("output_dir", "instruments/banks")).resolve()
    base_dir = rules.get("bank_base_dir", "../swi")
    per_file = int(rules.get("max_programs_per_file", 128))

    swis = sorted(input_dir.glob("*.swi"))
    if not swis:
        raise SystemExit(f"No .swi files found in {input_dir}")

    # Group by bank id.
    grouped: Dict[str, List[Path]] = {}
    for p in swis:
        bid = classify(p.name, rules)
        grouped.setdefault(bid, []).append(p)

    # Always provide an "all" bank (paged).
    grouped.setdefault("all", [])
    grouped["all"] = list(swis)

    # Bank label lookup.
    labels: Dict[str, str] = {b["id"]: b.get("label", b["id"]) for b in rules.get("banks", [])}
    labels[rules.get("fallback_bank", {}).get("id", "misc")] = rules.get("fallback_bank", {}).get("label", "Misc")
    labels["all"] = "All"

    index: dict = {"base_dir": base_dir, "banks": {}}

    for bid, files in sorted(grouped.items()):
        pages: List[List[Path]] = [files[i : i + per_file] for i in range(0, len(files), per_file)]
        index["banks"][bid] = []
        for page_i, page in enumerate(pages):
            name = f"{labels.get(bid, bid)} ({page_i})"
            out = output_dir / f"bank-{bid}-{page_i}.swibank"
            mapping = {i: page[i].name for i in range(len(page))}
            if not args.dry_run:
                write_swibank(out, name=name, base_dir=base_dir, program_to_file=mapping)
            index["banks"][bid].append({"file": str(out.relative_to(repo_root)).replace('\\\\', '/'), "name": name, "programs": mapping})

    # Always emit a small GM drumkit example.
    dk_path = output_dir / "drumkit-gm.swibank"
    if not args.dry_run:
        write_gm_drumkit(dk_path, base_dir=base_dir)
    index["drumkit_gm"] = str(dk_path.relative_to(repo_root)).replace('\\\\', '/')

    # Curated "built-in" drumkit.
    dk2_path = output_dir / "drumkit-remid.swibank"
    if not args.dry_run:
        write_builtin_drumkit(dk2_path, base_dir=base_dir)
    index["drumkit_remid"] = str(dk2_path.relative_to(repo_root)).replace('\\\\', '/')

    idx_path = output_dir / "banks_index.json"
    if not args.dry_run:
        idx_path.write_text(json.dumps(index, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # Also write a copy into modgui/ so the MOD GUI can load it via its own resourcesDirectory.
    modgui_idx = repo_root / "modgui" / "banks_index.json"
    if not args.dry_run:
        modgui_idx.parent.mkdir(parents=True, exist_ok=True)
        modgui_idx.write_text(json.dumps(index, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"Input:  {input_dir}")
    print(f"Output: {output_dir}")
    print(f"Wrote:  {idx_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
